### ISSUE TITLE
ForbiddenError: Unable to load OAuth 2.0 transactions from session

### ISSUE THREAD

**Issue by LukeeeeBennett** [jaredhanson/oauth2orize#111]
When performing a __POST__ request to my `server.decision()`/`server.grant()` endpoint using _cUrl_ or _POSTMAN client_ I get a good response and I receive the auth code I need for a __POST__ request to my `server.token()`/`server.exchage()` endpoint.

However, when I generate a __POST__ request using Angulars `$http` service, I recieve the following error.

````
ForbiddenError: Unable to load OAuth 2.0 transactions from session
    at Object.transactionLoader [as handle] (/Users/user/workspace/project/api/node_modules/oauth2orize/lib/middleware/transactionLoader.js:37:42)
    at next_layer (/Users/user/workspace/project/api/node_modules/express/lib/router/route.js:103:13)
    at complete (/Users/user/workspace/project/api/node_modules/passport/lib/middleware/authenticate.js:243:13)
    at /Users/user/workspace/project/api/node_modules/passport/lib/middleware/authenticate.js:250:15
    at pass (/Users/user/workspace/project/api/node_modules/passport/lib/authenticator.js:427:14)
    at Authenticator.transformAuthInfo (/Users/user/workspace/project/api/node_modules/passport/lib/authenticator.js:449:5)
    at /Users/user/workspace/project/api/node_modules/passport/lib/middleware/authenticate.js:247:22
    at IncomingMessage.req.login.req.logIn (/Users/user/workspace/project/api/node_modules/passport-http/node_modules/passport/lib/passport/http/request.js:49:13)
    at BasicStrategy.strategy.success (/Users/user/workspace/project/api/node_modules/passport/lib/middleware/authenticate.js:228:13)
    at verified (/Users/user/workspace/project/api/node_modules/passport-http/lib/passport-http/strategies/basic.js:91:10)
````

I've done some searching through Google and the issues and I can't seem to find anything that can help me.

Can anyone point me in the right direction?

**Comment by LukeeeeBennett** [comment]
After some investigation I've found that in the error case, the script is failing to append the __authorize__ object as shown below. 

Successful request:
````javascript
{ cookie: 
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: true },
  authorize: 
   { Y7mWMFXy: 
      { protocol: 'oauth2',
        client: '[client_id]',
        redirectURI: 'oob',
        req: [Object] } } }
````

Unsuccessful request:
````javascript
{ cookie: 
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: true },
}
````

**Comment by klebba** [comment]
@LukeeeeBennett -- can you give more info about your workaround? I hit the same error

**Comment by MohamadAtieh** [comment]
hey guys, I found this repo explaining everything so well. 

https://github.com/FrankHassanabad/Oauth2orizeRecipes

**Comment by cookiejest** [comment]
is there anymore info on this? I am getting the ssame issue but struggling to find info on immediate callback

**Comment by markstos** [comment]
@cookiejest Did the "Recipes" link above help?

**Comment by xuan9230** [comment]
This error means your server cannot find a related session.

Possible reasons:
1. request header doesn't contain the cookie (which distinguishes session). e.g. `axios` has an option `withCredentials: true` that allows cookie traffics
2. server is not configured to allow `Access-Control-Allow-Credentials` CORS header. e.g. if you use `cors` with `express` there's an option: `credentials: true`
3. origins are different - endpoint of your first request is different from the endpoint of other request, causing them unable to share the session
