### ISSUE TITLE
Failed to obtain access token

### ISSUE THREAD

**Issue by CozmaSerban** [jaredhanson/oauth2orize#129]
Hello,
I have a problem and i can`t get the access token.In other words i checked and i can`t make the exchange between the authorization code and the access token.I also checked the db and there are authcodes saved. This error appers on the callback redirect after the client authorised..

Failed to obtain access token

InternalOAuthError: Failed to obtain access token
    at OAuth2Strategy._createOAuthError (C:\Users\Serban\Desktop\JDL-client-test\node_modules\passport-oauth2\lib\strategy.js:348:17)
    at C:\Users\Serban\Desktop\JDL-client-test\node_modules\passport-oauth2\lib\strategy.js:171:43
    at C:\Users\Serban\Desktop\JDL-client-test\node_modules\passport-oauth2\node_modules\oauth\lib\oauth2.js:176:18
    at passBackControl (C:\Users\Serban\Desktop\JDL-client-test\node_modules\passport-oauth2\node_modules\oauth\lib\oauth2.js:123:9)
    at IncomingMessage.<anonymous> (C:\Users\Serban\Desktop\JDL-client-test\node_modules\passport-oauth2\node_modules\oauth\lib\oauth2.js:142:7)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by Mague** [comment]
verifica que estas incluyendo la libreria de body-parser
