### ISSUE TITLE
Error When creating a new BearerStrategy

### ISSUE THREAD

**Issue by saransh2012** [jaredhanson/oauth2orize#45]
I am using the same as example but getting this error. Please can anyone help?
if (!name) throw new Error('authentication strategies must have a name');
                   ^
Error: authentication strategies must have a name
    at Passport.use (/Users/saransh2012/Developer/vypics/node_modules/passport/lib/passport/index.js:51:20)
    at Object.<anonymous> (/Users/saransh2012/Developer/vypics/android_app/auth.js:54:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/saransh2012/Developer/vypics/android_app/app.js:11:1)
    at Module._compile (module.js:456:26)

**Comment by johnnycamby** [comment]
Hey 
- check if u have instantiated your local strategy  before you call passport to use your newly created strategy . 
Something like this  ::

var passport = require('passport');
var LocalStrategy = require('passport-local').Strategy;
var registerStrategy = new LocalStrategy({}, function(){});   <==  (Hey check instantiating line in you code to see if your missing a 'new' keyword)

passport.use('local-register', registerStrategy);
