### ISSUE TITLE
AuthorizationError: not authorized

### ISSUE THREAD

**Issue by kevinian** [jaredhanson/oauth2orize#91]
Hello, 

I tried the example provider and consumer, but I get the following error.
Who can explain me why will this occurs?

Express
500 AuthorizationError: not authorized
at validated (/home/kevin/oauth2orize/examples/all-grants/node_modules/oauth2orize/lib/middleware/authorization.js:131:36)
at /home/kevin/oauth2orize/examples/all-grants/oauth2.js:180:14
at Object.exports.findByClientId (/home/kevin/oauth2orize/examples/all-grants/db/clients.js:24:10)
at exports.authorization.res.render.transactionID (/home/kevin/oauth2orize/examples/all-grants/oauth2.js:174:16)
at /home/kevin/oauth2orize/examples/all-grants/node_modules/oauth2orize/lib/middleware/authorization.js:167:9
at pass (/home/kevin/oauth2orize/examples/all-grants/node_modules/oauth2orize/lib/server.js:262:26)
at pass (/home/kevin/oauth2orize/examples/all-grants/node_modules/oauth2orize/lib/server.js:280:9)
at pass (/home/kevin/oauth2orize/examples/all-grants/node_modules/oauth2orize/lib/server.js:271:11)
at Server._parse (/home/kevin/oauth2orize/examples/all-grants/node_modules/oauth2orize/lib/server.js:285:5)
at authorization (/home/kevin/oauth2orize/examples/all-grants/node_modules/oauth2orize/lib/middleware/authorization.js:118:12)

Best regards,
Kevin

**Comment by sgarbesi** [comment]
@trevorallred I added an answer to your StackOverflow question. I ran into the same problem as well, hope it fixes your problem.
